export const GET_TOP_MOVIES = 'GET_TOP_MOVIES';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const SET_LOADING = 'SET_LOADING';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_UPCOMING = 'GET_UPCOMING ';