export const GET_TOP_MOVIES = 'GET_TOP_MOVIES';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';
export const GET_SEARCH_SHOWS = 'GET_SEARCH_SHOWS';
export const SET_LOADING = 'SET_LOADING';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_UPCOMING = 'GET_UPCOMING ';
export const SET_ERRORS = 'SET_ERRORS';
export const GET_POPULAR_SHOWS = 'GET_POPULAR_SHOWS';
